sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sparkymaster/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sparkymaster/docker-react npm run test